### ISSUE TITLE
Create a sample to show a real k8s operator

### ISSUE THREAD

**Issue by unaizorrilla** [Xabaril/lucecu#14]
Create a sample or reference it from the template to show a real k8s operator on @dotnet! We can use the operator created for https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks.

cc @CarlosLanderas

**Comment by Xavgra** [comment]
Unai, it'll enough if we just add the links to the health checks  project in the __ProjectName__Operator class? https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.UI.K8s.Operator/Controller/HealthChecksController.cs
