### ISSUE TITLE
HealthChecks not found after applying ./HealthCheck_crd_definition.yaml 

### ISSUE THREAD

**Issue by Xavgra** [Xabaril/lucecu#15]
After applying the Deployment/HealthCheck_cdr_definition.yaml, healthcheks are not found but CRD are created.  

Doc. used as documentation : https://github.com/Xabaril/lucecu/blob/docs/docs/GettingStarted-K8SOperator.md
  
![image](https://user-images.githubusercontent.com/4202334/79121716-3c646400-7d96-11ea-8a29-c4f4b7f633f5.png)

**Comment by unaizorrilla** [comment]
Hi xavgra!!

K8SOperator template create two yaml files by default, the first one to create the CRD definition

https://github.com/Xabaril/lucecu/blob/master/src/templates/k8soperator/Content/Deployment/%7B%7Bcrdname%7D%7D_crd_definition.yaml

and the second one a sample to create a new CRD

 https://github.com/Xabaril/lucecu/blob/master/src/templates/k8soperator/Content/Deployment/create_new_%7B%7Bcrdname%7D%7D.yaml

Are you deployed create_new template to create a new crd instance?

**Comment by Xavgra** [comment]
Hi Unai

Right now, I've deployed the create_new file and the healthchecks are found, so you were right. May I suggest to add this step in the documentation? I can do it myself.
