### ISSUE TITLE
Some initial feedback

### ISSUE THREAD

**Issue by rynowak** [Xabaril/lucecu#2]
This is awesome! I've left some feedback here after doing a readthrough of the code. 

Lots of positive things:

- This is well thought out and seems useful
- I think it's really great to see logging and diagnostics built in from the beginning. My experience writing a `MutatingWebHook` is that it's pretty hard to see what's going on if you don't obsess about logging. 
- Instructions and docs are very clear

---

There's a much bigger set of features that would be needed to make an operator that watches multiple resources. You'd need multiple watcher loops. 

Most of the golang operator code I've seen has your register interest in multiple different resource types so they can all be watched.

---

Some things I found poking around the repo:

[Acknowledgements](https://github.com/Xabaril/lucecu#acknowledgements) should probably be updated - this looks like a copy-paste. 

Users running locally will hit this bug: https://github.com/kubernetes-client/csharp/issues/409 if they have multiple files in `KUBECONFIG`. This reported recently on dotnet/tye and it's a missing feature in the k8s sdk for .net. Just something to be aware of if someone reports this.

Adding an extra `.Abstractions` to namespaces [here](https://github.com/Xabaril/lucecu/blob/master/src/templates/k8soperator/Content/Crd/Abstractions/CustomResource.cs#L4) seems unnecessary. One of the first things I would change in a scaffolded project.  These classes feel like they belong in the k8s SDK.

The [group name](https://github.com/Xabaril/lucecu/blob/master/src/templates/k8soperator/Content/Crd/CRDConstants.cs#L5) should probably be a template parameter instead of hardcoded. 

Is this `1` supposed to be [there](https://github.com/Xabaril/lucecu/blob/master/src/templates/k8soperator/Content/Deployment/create_new_%7B%7Bcrdname%7D%7D.yaml#L4)?

You might want the plural to be a template parameter as well instead of a hardcoded `s` - https://github.com/Xabaril/lucecu/blob/master/src/templates/k8soperator/Content/Deployment/%7B%7Bcrdname%7D%7D_crd_definition.yaml#L8

It might be nice to have to comments calling out the places you're expected to edit. [example](https://github.com/Xabaril/lucecu/blob/master/src/templates/k8soperator/Content/Deployment/%7B%7Bcrdname%7D%7D_crd_definition.yaml#L22) For instance what I'm suggesting is a comment there saying "hey edit this to flesh out your data model" and then a similar comment in the C# data model. Make it easier to find the things the user should edit. Another idea would be to put all of the *framework* code in a specific folder, and all of the code the user edits in the top-level. 

You probably want a `Task.Yield`: [here])https://github.com/Xabaril/lucecu/blob/master/src/templates/k8soperator/Content/Operator/__ProjectName__Operator.cs#L33) - if a worker processes a lot of synchronous work it can *block* init of other services. I doubt this is going to happen in your case, but I always add this.

You should think about some error-handling/logging [here](https://github.com/Xabaril/lucecu/blob/master/src/templates/k8soperator/Content/Operator/__ProjectName__Operator.cs#L33). The hosted service infrastructure doesn't log when a hosted service crashes :(.

At [this point](https://github.com/Xabaril/lucecu/blob/master/src/templates/k8soperator/Content/Program.cs#L27) I see you're not actually using hosted services 😆 Is there a reason why this isn't using generic host with the console lifetime? I would expect most of the code in `Program.cs` except the DI stuff could go away. 

You might want to have special error handling for the case where your CRD is not registerred. https://github.com/Xabaril/lucecu/blob/master/src/templates/k8soperator/Content/Operator/__ProjectName__Operator.cs#L46 - this would be a common mistake to make, and I think right now it would crash the operator.

**Comment by rynowak** [comment]
@davidfowl

**Comment by unaizorrilla** [comment]
Hi @rynowak 

Thansk for the feedback, awesome as always! I'm going to  split the feedback on different issues and address as soon as posible!

**Comment by davidfowl** [comment]
This is great! Also beware of overlapping events. It’s likely that you have lots of implicit async void calls. I would use a channel to queue those operations and ensure order or make the code robust against handling multiple overlapping calls.

**Comment by unaizorrilla** [comment]
Hi @davidfowl 

thanks for the feedback!!!  I will create a issue for following this!

**Comment by unaizorrilla** [comment]
Hi @rynowak and @davidfowl 

We are working past days to solve the issues you fill:

-  Include code comments on files to be edited:

https://github.com/Xabaril/lucecu/blob/master/src/templates/k8soperator/Content/Crd/%7B%7Bcrdname%7D%7DResourceSpec.cs

https://github.com/Xabaril/lucecu/blob/master/src/templates/k8soperator/Content/Deployment/Crd/%7B%7Bcrdname%7D%7D_crd_definition.yaml

- Add crd plural name on parameters

We include also new parameters needed for operator deployment ( image name and operator name with appropiate coalesce on existing parameters 

https://github.com/Xabaril/lucecu/blob/master/src/templates/k8soperator/Content/.template.config/template.json


- Use of GenericHost

Operator is created with worker template and use the same things ( generic host and hosted service )

https://github.com/Xabaril/lucecu/blob/master/src/templates/k8soperator/Content/Program.cs

- Removed unnecesary folder ( abstractions ) and  added operator template yaml files

https://github.com/Xabaril/lucecu/tree/master/src/templates/k8soperator/Content/Deployment/Operator


- Improved resilience with Channels

https://github.com/Xabaril/lucecu/tree/master/src/templates/k8soperator/Content/Deployment/Operator 

- More on docs and samples

We include a operator sample (City Weather)  

https://github.com/Xabaril/lucecu/tree/master/src/templates/k8soperator/Content/Deployment/Operator 

and use this template for the HealthChecks UI operator 

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/tree/master/src/HealthChecks.UI.K8s.Operator
