### ISSUE TITLE
Group name is not populated from template params to constants

### ISSUE THREAD

**Issue by unaizorrilla** [Xabaril/lucecu#9]
Related with #2 by @rynowak

"You might want the plural to be a template parameter as well instead of a hardcoded s - https://github.com/Xabaril/lucecu/blob/master/src/templates/k8soperator/Content/Deployment/%7B%7Bcrdname%7D%7D_crd_definition.yaml#L8"

Group name is already a template parameter, but is not populated yet to constants

**Comment by Xavgra** [comment]
Pull request https://github.com/Xabaril/lucecu/pull/16

**Comment by unaizorrilla** [comment]
Closed by #16
